apiVersion: v1
kind: Service
metadata:
  name: user-webapp-service
  labels: 
    app: user-webapp
spec:
  type: LoadBalancer
  selector:
    app: user-webapp
  ports: 
    - port: 80
      targetPort: 8080
