apiVersion: apps/v1
kind: Deployment 
metadata:
  name: user-webapp
  labels:
    app: user-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-webapp
  template:  
    metadata:
      labels: 
        app: user-webapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: user-webapp
          image: felixgokmen/webapp:0.1
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080           
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "webappdb"            
            - name: DB_USERNAME
              value: "felix@akswebappdb"            
            - name: DB_PASSWORD
              value: "admin123?"            
