apiVersion: v1
kind: Service
metadata:
  name: deployment1-loadbalancer
  labels:
    app: deployment1
spec:
  type: LoadBalancer
  selector:
    app: deployment1
  ports:
    - port: 80
      targetPort: 80
