apiVersion: v1
kind: Service
metadata:
  name: back-end-service #
  labels:
    app: back-end
    tier: backend   
spec:
  
  selector:
    app: back-end
  ports:
    - name: http
      port: 8080 
      targetPort: 8080 
