apiVersion: v1
kind: Service 
metadata:
  name: frontend-service
  labels:
    app: frontend
    tier: frontend  
spec:
  type: LoadBalancer 
  selector:
    app: frontend
  ports: 
    - name: http
      port: 80 
      targetPort: 80 