apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksvncluster-deployment
  labels:
    app: aksvncluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksvncluster
  template:
    metadata:
      labels:
        app: aksvncluster
    spec:
      containers:
        - name: aksvncluster
          image: aksvmregistry.azurecr.io/webapp/azure-nginx:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            