apiVersion: v1
kind: Service
metadata:
  name: aksvncluster-service
  labels:
    app: aksvncluster
spec:
  type: LoadBalancer
  selector:
    app: aksvncluster
  ports:
    - port: 80
      targetPort: 80