apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-ca
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mwebapp-app
        image: felixgokmen/webapp:0.1